### ISSUE TITLE
Precalculate Galois.multiply results

### ISSUE THREAD

**Issue by klauspost** [Backblaze/JavaReedSolomon#3]
You can pre-calculate results of Galois.multiply into a 64KB 2D table. This also gets rid of the branching.

I am porting the library to Go, and for me that gives a nice speed-up (~30%), and I suspect it will be even more in Java.

**Comment by bwbeach** [comment]
That's interesting.  The papers I read didn't think that using a multiplication table would be any faster than the logarithm table I'm using.  And the multiplication table is bigger than the L1 cache on the Intel processors we use, so that made sense.  Sounds like it's worth taking the time to profile both.

I'd love to see your Go version when you're done.  It's on my list of languages to learn soon.

**Comment by klauspost** [comment]
Looking forward to your results. Of course L2 is slower, but it does save two look-ups and the branching.

[The port is fully operational](https://github.com/klauspost/reedsolomon), including tests, but I need to write documentation for it before I formally release it. 

I will of course link to here and your blog post.

**Comment by bwbeach** [comment]
Cool.  Thanks.

**Comment by bwbeach** [comment]
I tried all 12 permutations of: log table vs multiplication table, and all six orderings of the nested loops.  There are clear winners.  The Intel documentation says that there is a hardware optimization for code that runs through memory in order.  My guess is that the loop orderings that win are taking advantage of that.  They wind up writing the output shards 17 times each (in my 17+3 coding), and reading each input shard 3 times, but far outperform the ones that write each output shard only once.

Take a look at the chart I posted in the README.

I'm going to close this issue, because I think this is as good as the Java code is going to get.
