### ISSUE TITLE
dataShardCount >= 257 creates singular matrix

### ISSUE THREAD

**Issue by klauspost** [Backblaze/JavaReedSolomon#5]
I was quite surprised when I found this.

After researching a bit, I found this in the blog post:

>The math—and the code—works with any numbers as long as you have at least one data shard and don’t have more than 256 shards total.

If there is no way for this to work on bigger shard numbers, it should be mentioned in the library, and you should check it in the constructor.

Also - is the above correct? Shouldn't it be "and don’t have more than 256 DATA shards ~~total~~". I don't have any problem creating an encoder with 256 data and 256 parity shards. But as soon as there is more than 256 data shards it fails.

**Comment by bwbeach** [comment]
Plank's paper says that the total number of shards can't be more than 256.  I don't know if the math works for 256 + 256.  The question is whether every 256-row subset of the 512x256 matrix has an inverse.

I like the idea of putting a check in the constructor.  For now, I think I'll require that the total be <= 256, just to be safe.

**Comment by klauspost** [comment]
Yeah, I think testing it and adding it to the docs is the way to go.

**Comment by bwbeach** [comment]
I tested some combinations with lots of shards, making sure that you could construct an inverse matrix for every possible subset of shards.  It worked up to 248(data) + 256(parity).  Because I don't understand the math well enough to know why the limit is there, I added a check in the constructor that throws an exception if the  **total** number of shards exceeds 256, along with a comment explaining it.

**Comment by templexxx** [comment]
What Plank mean is "vandermonde matrix will be MDS as long as < 2^w(w = 8 here) ". And this matrix is non-systematic,it's a vandermonde matrix. I think it's not so hard to understand it, because the basenum is the row number,and the row number must < 256 (because its in a galois field) otherwise you will have two same basenum, the second one will be useful for recovering data,so it won't be MDS.

**Comment by templexxx** [comment]
file:///Users/templex/Pictures/screenshot.snapndraglibrary/bb90059b2/screenshot_17.jpg

**Comment by templexxx** [comment]
![mds](https://cloud.githubusercontent.com/assets/13476726/21217301/7a9c8f40-c2e6-11e6-8113-cdeedc39f68c.jpg)
