### ISSUE TITLE
why did you say: vandermonde matrix doesn't have the property that the data shards are unchanged after encoding?

### ISSUE THREAD

**Issue by templexxx** [Backblaze/JavaReedSolomon#8]
In the reedsolomon.java (lines: 311)  I found that:

![image](https://cloud.githubusercontent.com/assets/13476726/15216342/498535ae-1889-11e6-911d-a8d2d88be4a8.png)

Is that right? :
 identity matrix * data shards = data shards
Vandermonde matrix * data shards = parity shards

If it's right. The Vandermonde matrix can't change the data shards at all 

Thank you for your patience!

**Comment by bwbeach** [comment]
The full encoding matrix produces both the data shards and parity shards:

    encoding_matrix * data_shards = (data_shards and parity_shards)

The top part of the encoding matrix needs to be an identity matrix if you want the data shards to come through unchanged.

I did a quick tutorial video that you might find helpful: https://www.youtube.com/watch?v=jgO09opx56o

**Comment by templexxx** [comment]
Thank you for your reply!
It really helps me a lot
Thank you!

**Comment by templexxx** [comment]
I read the ISA-L(intel's rs code lib) codes, and I found they have different way to make encoding matrix.Intel make a identity matrix directly,then put a vandermonde/cauchy matrix under it. So they dont have to calculate the inverse matrix of the top. maybe that's clearer way

**Comment by DrPizza** [comment]
@templexxx ISA-L's documentation says that its RS matrix generator can produce matrices that aren't invertible, which seems less than useful.

jerasure seems to use a similar approach to the Backblaze code; it generates a Vandermonde matrix, then performs operations to convert the top left into an identity matrix (to offer the property that the data shards are passed in unchanged). It also goes a step further, and ensures that the first parity shard is straight XOR parity. For reasons that are less clear to me, it additionally manipulates the coding matrix so that the first column is always 1.

**Comment by templexxx** [comment]
@DrPizza   I made a calculation here :https://github.com/01org/isa-l/issues/13. It proved intel's way may not work. JavaReedSolomon has a better way.

**Comment by templexxx** [comment]
@DrPizza maybe XOR will be faster?

**Comment by DrPizza** [comment]
I suppose it could be if the all-1s row were treated specially, but it isn't. I suspect it's so that you can use it for N+1 it automatically gives you RAID 5-style XOR, without having to do any special handling anywhere else.

**Comment by templexxx** [comment]
@DrPizza Yeah...maybe you are right. We need care about compatibility in practice

**Comment by bwbeach** [comment]
I agree that compatibility is important.  

Simplicity is also good.  It's a sufficient reason for not have a special case where one row is XOR. 

In practice we have found that the cost of the Reed-Solomon computation is not significant in running the Backblaze B2 service.
